name: catia-and-jamie
services:
  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    environment:
      - ORIGIN=http://localhost
    ports:
      - 3000:3000
    networks:
      - api
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      - DATABASE_USERNAME=[USERNAME]
      - DATABASE_PASSWORD=[PASSWORD]
      - DATABASE_HOST=[HOST]
      - DATABASE_NAME=[NAME]
      - OPENSSL_ENCRYPTION_KEY=[RANDOM 32 CHARS]
      - SESSION_SECRET=[RANDOM 32 CHARS]
    ports:
      - 5005:5005
    networks:
      - api
      - backend
    volumes:
      - ./assets:./backend/assets
    depends_on:
      - database
  database:
    image: postgres:16.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=[USERNAME]
      - POSTGRES_PASSWORD=[PASSWORD]
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - database:/var/lib/postgresql/data
  nginx:
    build:
      context: ./nginx
    restart: unless-stopped
    ports:
      - 8371:8371
    networks:
      - api
    depends_on:
      - frontend
networks:
  backend: {}
  api: {}
volumes:
  database:
    driver: local